<?php
/**
 * Payment
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  TebexCheckout
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Tebex Checkout API
 *
 * The Checkout APIs are designed to allow our creators to use the Tebex Checkout flow and payment acceptance capabilities without the need to set up a Tebex-powered webstore. Using these APIs allows you to create baskets with custom products (as opposed to pre-created products on our webstore platform), and send customers directly to the checkout flow to proceed with payment options.  You must receive prior authorisation before the Checkout API is enabled on your account. Please contact customer support or your account manager to discover if you qualify to use the Checkout API before beginning integration.
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: tebex-integrations@overwolf.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TebexCheckout\Model;

use \ArrayAccess;
use \TebexCheckout\ObjectSerializer;

/**
 * Payment Class Doc Comment
 *
 * @category Class
 * @package  TebexCheckout
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Payment implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Payment';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'transaction_id' => 'string',
        'status' => '\TebexCheckout\Model\PaymentStatus',
        'payment_sequence' => 'string',
        'created_at' => '\DateTime',
        'price' => '\TebexCheckout\Model\PaymentPrice',
        'price_paid' => '\TebexCheckout\Model\PaymentPrice',
        'payment_method' => '\TebexCheckout\Model\PaymentPaymentMethod',
        'revenue_share' => '\TebexCheckout\Model\RevenueShare[]',
        'decline_reason' => 'string',
        'fees' => '\TebexCheckout\Model\PaymentFees',
        'customer' => '\TebexCheckout\Model\PaymentCustomer',
        'products' => '\TebexCheckout\Model\PaymentProductsInner[]',
        'coupons' => 'object[]',
        'gift_cards' => 'object[]',
        'recurring_payment_reference' => 'string',
        'custom' => 'object'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'transaction_id' => null,
        'status' => null,
        'payment_sequence' => null,
        'created_at' => 'date-time',
        'price' => null,
        'price_paid' => null,
        'payment_method' => null,
        'revenue_share' => null,
        'decline_reason' => null,
        'fees' => null,
        'customer' => null,
        'products' => null,
        'coupons' => null,
        'gift_cards' => null,
        'recurring_payment_reference' => null,
        'custom' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'transaction_id' => false,
        'status' => false,
        'payment_sequence' => false,
        'created_at' => false,
        'price' => false,
        'price_paid' => false,
        'payment_method' => false,
        'revenue_share' => false,
        'decline_reason' => false,
        'fees' => false,
        'customer' => false,
        'products' => false,
        'coupons' => false,
        'gift_cards' => false,
        'recurring_payment_reference' => true,
        'custom' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'transaction_id' => 'transaction_id',
        'status' => 'status',
        'payment_sequence' => 'payment_sequence',
        'created_at' => 'created_at',
        'price' => 'price',
        'price_paid' => 'price_paid',
        'payment_method' => 'payment_method',
        'revenue_share' => 'revenue_share',
        'decline_reason' => 'decline_reason',
        'fees' => 'fees',
        'customer' => 'customer',
        'products' => 'products',
        'coupons' => 'coupons',
        'gift_cards' => 'gift_cards',
        'recurring_payment_reference' => 'recurring_payment_reference',
        'custom' => 'custom'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'transaction_id' => 'setTransactionId',
        'status' => 'setStatus',
        'payment_sequence' => 'setPaymentSequence',
        'created_at' => 'setCreatedAt',
        'price' => 'setPrice',
        'price_paid' => 'setPricePaid',
        'payment_method' => 'setPaymentMethod',
        'revenue_share' => 'setRevenueShare',
        'decline_reason' => 'setDeclineReason',
        'fees' => 'setFees',
        'customer' => 'setCustomer',
        'products' => 'setProducts',
        'coupons' => 'setCoupons',
        'gift_cards' => 'setGiftCards',
        'recurring_payment_reference' => 'setRecurringPaymentReference',
        'custom' => 'setCustom'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'transaction_id' => 'getTransactionId',
        'status' => 'getStatus',
        'payment_sequence' => 'getPaymentSequence',
        'created_at' => 'getCreatedAt',
        'price' => 'getPrice',
        'price_paid' => 'getPricePaid',
        'payment_method' => 'getPaymentMethod',
        'revenue_share' => 'getRevenueShare',
        'decline_reason' => 'getDeclineReason',
        'fees' => 'getFees',
        'customer' => 'getCustomer',
        'products' => 'getProducts',
        'coupons' => 'getCoupons',
        'gift_cards' => 'getGiftCards',
        'recurring_payment_reference' => 'getRecurringPaymentReference',
        'custom' => 'getCustom'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('transaction_id', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('payment_sequence', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('price_paid', $data ?? [], null);
        $this->setIfExists('payment_method', $data ?? [], null);
        $this->setIfExists('revenue_share', $data ?? [], null);
        $this->setIfExists('decline_reason', $data ?? [], null);
        $this->setIfExists('fees', $data ?? [], null);
        $this->setIfExists('customer', $data ?? [], null);
        $this->setIfExists('products', $data ?? [], null);
        $this->setIfExists('coupons', $data ?? [], null);
        $this->setIfExists('gift_cards', $data ?? [], null);
        $this->setIfExists('recurring_payment_reference', $data ?? [], null);
        $this->setIfExists('custom', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets transaction_id
     *
     * @return string|null
     */
    public function getTransactionId()
    {
        return $this->container['transaction_id'];
    }

    /**
     * Sets transaction_id
     *
     * @param string|null $transaction_id transaction_id
     *
     * @return self
     */
    public function setTransactionId($transaction_id)
    {
        if (is_null($transaction_id)) {
            throw new \InvalidArgumentException('non-nullable transaction_id cannot be null');
        }
        $this->container['transaction_id'] = $transaction_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \TebexCheckout\Model\PaymentStatus|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \TebexCheckout\Model\PaymentStatus|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets payment_sequence
     *
     * @return string|null
     */
    public function getPaymentSequence()
    {
        return $this->container['payment_sequence'];
    }

    /**
     * Sets payment_sequence
     *
     * @param string|null $payment_sequence payment_sequence
     *
     * @return self
     */
    public function setPaymentSequence($payment_sequence)
    {
        if (is_null($payment_sequence)) {
            throw new \InvalidArgumentException('non-nullable payment_sequence cannot be null');
        }
        $this->container['payment_sequence'] = $payment_sequence;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets price
     *
     * @return \TebexCheckout\Model\PaymentPrice|null
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param \TebexCheckout\Model\PaymentPrice|null $price price
     *
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            throw new \InvalidArgumentException('non-nullable price cannot be null');
        }
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets price_paid
     *
     * @return \TebexCheckout\Model\PaymentPrice|null
     */
    public function getPricePaid()
    {
        return $this->container['price_paid'];
    }

    /**
     * Sets price_paid
     *
     * @param \TebexCheckout\Model\PaymentPrice|null $price_paid price_paid
     *
     * @return self
     */
    public function setPricePaid($price_paid)
    {
        if (is_null($price_paid)) {
            throw new \InvalidArgumentException('non-nullable price_paid cannot be null');
        }
        $this->container['price_paid'] = $price_paid;

        return $this;
    }

    /**
     * Gets payment_method
     *
     * @return \TebexCheckout\Model\PaymentPaymentMethod|null
     */
    public function getPaymentMethod()
    {
        return $this->container['payment_method'];
    }

    /**
     * Sets payment_method
     *
     * @param \TebexCheckout\Model\PaymentPaymentMethod|null $payment_method payment_method
     *
     * @return self
     */
    public function setPaymentMethod($payment_method)
    {
        if (is_null($payment_method)) {
            throw new \InvalidArgumentException('non-nullable payment_method cannot be null');
        }
        $this->container['payment_method'] = $payment_method;

        return $this;
    }

    /**
     * Gets revenue_share
     *
     * @return \TebexCheckout\Model\RevenueShare[]|null
     */
    public function getRevenueShare()
    {
        return $this->container['revenue_share'];
    }

    /**
     * Sets revenue_share
     *
     * @param \TebexCheckout\Model\RevenueShare[]|null $revenue_share revenue_share
     *
     * @return self
     */
    public function setRevenueShare($revenue_share)
    {
        if (is_null($revenue_share)) {
            throw new \InvalidArgumentException('non-nullable revenue_share cannot be null');
        }
        $this->container['revenue_share'] = $revenue_share;

        return $this;
    }

    /**
     * Gets decline_reason
     *
     * @return string|null
     */
    public function getDeclineReason()
    {
        return $this->container['decline_reason'];
    }

    /**
     * Sets decline_reason
     *
     * @param string|null $decline_reason decline_reason
     *
     * @return self
     */
    public function setDeclineReason($decline_reason)
    {
        if (is_null($decline_reason)) {
            throw new \InvalidArgumentException('non-nullable decline_reason cannot be null');
        }
        $this->container['decline_reason'] = $decline_reason;

        return $this;
    }

    /**
     * Gets fees
     *
     * @return \TebexCheckout\Model\PaymentFees|null
     */
    public function getFees()
    {
        return $this->container['fees'];
    }

    /**
     * Sets fees
     *
     * @param \TebexCheckout\Model\PaymentFees|null $fees fees
     *
     * @return self
     */
    public function setFees($fees)
    {
        if (is_null($fees)) {
            throw new \InvalidArgumentException('non-nullable fees cannot be null');
        }
        $this->container['fees'] = $fees;

        return $this;
    }

    /**
     * Gets customer
     *
     * @return \TebexCheckout\Model\PaymentCustomer|null
     */
    public function getCustomer()
    {
        return $this->container['customer'];
    }

    /**
     * Sets customer
     *
     * @param \TebexCheckout\Model\PaymentCustomer|null $customer customer
     *
     * @return self
     */
    public function setCustomer($customer)
    {
        if (is_null($customer)) {
            throw new \InvalidArgumentException('non-nullable customer cannot be null');
        }
        $this->container['customer'] = $customer;

        return $this;
    }

    /**
     * Gets products
     *
     * @return \TebexCheckout\Model\PaymentProductsInner[]|null
     */
    public function getProducts()
    {
        return $this->container['products'];
    }

    /**
     * Sets products
     *
     * @param \TebexCheckout\Model\PaymentProductsInner[]|null $products products
     *
     * @return self
     */
    public function setProducts($products)
    {
        if (is_null($products)) {
            throw new \InvalidArgumentException('non-nullable products cannot be null');
        }
        $this->container['products'] = $products;

        return $this;
    }

    /**
     * Gets coupons
     *
     * @return object[]|null
     */
    public function getCoupons()
    {
        return $this->container['coupons'];
    }

    /**
     * Sets coupons
     *
     * @param object[]|null $coupons coupons
     *
     * @return self
     */
    public function setCoupons($coupons)
    {
        if (is_null($coupons)) {
            throw new \InvalidArgumentException('non-nullable coupons cannot be null');
        }
        $this->container['coupons'] = $coupons;

        return $this;
    }

    /**
     * Gets gift_cards
     *
     * @return object[]|null
     */
    public function getGiftCards()
    {
        return $this->container['gift_cards'];
    }

    /**
     * Sets gift_cards
     *
     * @param object[]|null $gift_cards gift_cards
     *
     * @return self
     */
    public function setGiftCards($gift_cards)
    {
        if (is_null($gift_cards)) {
            throw new \InvalidArgumentException('non-nullable gift_cards cannot be null');
        }
        $this->container['gift_cards'] = $gift_cards;

        return $this;
    }

    /**
     * Gets recurring_payment_reference
     *
     * @return string|null
     */
    public function getRecurringPaymentReference()
    {
        return $this->container['recurring_payment_reference'];
    }

    /**
     * Sets recurring_payment_reference
     *
     * @param string|null $recurring_payment_reference recurring_payment_reference
     *
     * @return self
     */
    public function setRecurringPaymentReference($recurring_payment_reference)
    {
        if (is_null($recurring_payment_reference)) {
            array_push($this->openAPINullablesSetToNull, 'recurring_payment_reference');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('recurring_payment_reference', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['recurring_payment_reference'] = $recurring_payment_reference;

        return $this;
    }

    /**
     * Gets custom
     *
     * @return object|null
     */
    public function getCustom()
    {
        return $this->container['custom'];
    }

    /**
     * Sets custom
     *
     * @param object|null $custom custom
     *
     * @return self
     */
    public function setCustom($custom)
    {
        if (is_null($custom)) {
            throw new \InvalidArgumentException('non-nullable custom cannot be null');
        }
        $this->container['custom'] = $custom;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


